/**
 * Attribute schema for `rmp/menu-items`.
 *
 * Kept in its own module so the block registration and its deprecations can
 * both read it without importing each other in a cycle. It is mirrored in
 * `blocks/block.php` — WordPress drops any attribute a server-side render
 * callback has not declared, so the two lists must stay in step.
 */

export const MENU_ITEMS_ATTRIBUTES = {
	id: {
		type: 'string',
	},
	menuStyle: {
		type: 'object',
		default: {
			itemHeight: 40,
			lineHeight: 40,
			padding: {
				top: '5px',
				right: '5px',
				bottom: '5px',
				left: '5px',
			},
			fontSize: '15px',
			fontWieght: 300,
			fontFamily: '',
			textAlign: 'left',
			letterSpacing: '',
			letterCase: '',
			wordWrap: '',
			color: '#ffffff',
			hoverColor: '#ffffff',
			activeColor: '#ffffff',
			activeHoverColor: '#ffffff',
			background: '',
			backgroundHover: '',
			backgroundActive: '#6fda44',
			backgroundActiveHover: '',
			border: {},
			borderHover: {},
			borderActive: {},
			borderActiveHover: {},
		},
	},
	submenuStyle: {
		type: 'object',
		default: {
			lineHeight: 40,
			padding: {
				top: '5px',
				right: '5px',
				bottom: '5px',
				left: '5px',
			},
			fontSize: '15px',
			fontWieght: 300,
			fontFamily: '',
			textAlign: 'left',
			letterSpacing: '',
			letterCase: '',
			wordWrap: '',
			color: '#ffffff',
			hoverColor: '#ffffff',
			activeColor: '#ffffff',
			activeHoverColor: '#ffffff',
			backgroundColor: '#6fda44',
			backgroundHoverColor: '#6fda44',
			backgroundActiveColor: '#6fda44',
			backgroundActiveHoverColor: '#6fda44',
			border: {},
			borderHover: {},
			borderActive: {},
			borderActiveHover: {},
		},
	},
	submenuBehaviour: {
		type: 'object',
		default: {
			useAccordion: '',
			autoExpandAllSubmenu: '',
			autoExpandCurrentSubmenu: '',
			expandSubItemOnParentClick: '',
			itemClickOpens: false,
			desktopTrigger: 'click',
		},
	},
	submenuIndentation: {
		type: 'object',
		default: {
			side: 'left',
			childLevel1: 5,
			childLevel2: 5,
			childLevel3: 5,
			childLevel4: 5,
		},
	},
	triggerIcon: {
		type: 'object',
		default: {
			type: 'text',
			textShape: '▼',
			activeTextShape: '▲',
			position: 'right',
			width: 45,
			height: 45,
			color: '#ffffff',
			hoverColor: '#ffffff',
			activeColor: '#ffffff',
			activeHoverColor: '#ffffff',
			backgroundColor: '',
			backgroundHoverColor: '',
			backgroundActiveColor: '',
			backgroundActiveHoverColor: '',
			border: {},
			borderHover: {},
			borderActive: {},
			borderActiveHover: {},
		},
	},
	desktopMenuStyle: {
		type: 'object',
		default: {
			color: '',
			hoverColor: '',
			activeColor: '',
			background: '',
			backgroundHover: '',
			backgroundActive: '',
			itemPadding: {},
			gap: 0,
			justify: 'flex-start',
			submenuColor: '',
			submenuHoverColor: '',
			submenuBackground: '',
			submenuBackgroundHover: '',
			submenuMinWidth: 200,
			submenuAnimation: 'fade',
			submenuAnimationSpeed: 200,
			dropdownAlign: 'left',
		},
	},
	responsive: {
		type: 'object',
		default: {},
	},
	blockStyles: {
		type: 'object',
	},
};
