import { registerBlockType } from '@wordpress/blocks';
import { __ } from '@wordpress/i18n';
import Edit from './edit';
import Save from './save';

registerBlockType('rmp/menu-items', {
	title: __('Menu items', 'responeive-menu'),
	description: __('Menu items', 'responeive-menu'),
	icon: 'editor-ul',
	parent: ['rmp/menu'],
	supports: {
		html: false,
		background: {
			backgroundImage: true,
			backgroundSize: true,
		},
		customClassName: true,
		spacing: {
			padding: true,
		},
	},
	attributes: {
		id: {
			type: 'string',
		},
		menuStyle: {
			type: 'object',
			default: {
				itemHeight: 40,
				lineHeight: 40,
				padding: {
					top: '5px',
					right: '5px',
					bottom: '5px',
					left: '5px',
				},
				fontSize: '15px',
				fontWieght: 300,
				fontFamily: '',
				textAlign: 'left',
				letterSpacing: '',
				letterCase: '',
				wordWrap: '',
				color: '#ffffff',
				hoverColor: '#ffffff',
				activeColor: '#ffffff',
				activeHoverColor: '#ffffff',
				background: '',
				backgroundHover: '',
				backgroundActive: '#6fda44',
				backgroundActiveHover: '',
				border: {},
				borderHover: {},
				borderActive: {},
				borderActiveHover: {},
			},
		},
		submenuStyle: {
			type: 'object',
			default: {
				lineHeight: 40,
				padding: {
					top: '5px',
					right: '5px',
					bottom: '5px',
					left: '5px',
				},
				fontSize: '15px',
				fontWieght: 300,
				fontFamily: '',
				textAlign: 'left',
				letterSpacing: '',
				color: '#ffffff',
				hoverColor: '#ffffff',
				activeColor: '#ffffff',
				activeHoverColor: '#ffffff',
				backgroundColor: '#6fda44',
				backgroundHoverColor: '#6fda44',
				backgroundActiveColor: '#6fda44',
				backgroundActiveHoverColor: '#6fda44',
				border: {},
				borderHover: {},
				borderActive: {},
				borderActiveHover: {},
			},
		},
		submenuBehaviour: {
			type: 'object',
			default: {
				useAccordion: '',
				autoExpandAllSubmenu: '',
				autoExpandCurrentSubmenu: '',
				expandSubItemOnParentClick: '',
			},
		},
		submenuIndentation: {
			type: 'object',
			default: {
				side: 'left',
				childLevel1: 5,
				childLevel2: 5,
				childLevel3: 5,
				childLevel4: 5,
			},
		},
		triggerIcon: {
			type: 'object',
			default: {
				type: 'text',
				textShape: '▼',
				activeTextShape: '▲',
				width: 45,
				height: 45,
				color: '#ffffff',
				hoverColor: '#ffffff',
				activeColor: '#ffffff',
				activeHoverColor: '#ffffff',
				backgroundColor: '',
				backgroundHoverColor: '',
				backgroundActiveColor: '',
				backgroundActiveHoverColor: '',
				border: {},
				borderHover: {},
				borderActive: {},
				borderActiveHover: {},
			},
		},
		blockStyles: {
			type: 'object',
		},
	},
	edit: Edit,
	save: Save,
});
