<?php

use ResponsiveMenu\Formatters\Tabs as Tabs;
use ResponsiveMenu\Formatters\FormElement as FormElement;
use ResponsiveMenu\Formatters\Text as Text;

?>

<div class="wrap">
	<h1>Responsive Menu Options</h1>
	<div class="tabs_container">
		<?php Tabs::render($this->options); ?>
	</div>
	<form method="post">
		<?php $t=1; foreach(Tabs::getTabs($this->options) as $key => $val) : ?>
			<div class="tab_container tab_container_<?php echo $t; ?>" id="tab_container_<?php echo $key; ?>">
				<h3><?php Text::underscoreToWord($key); ?></h3>
				<div class="options_container">
					<?php $i=0; foreach(Tabs::getTabOptions($key, $this->options) as $option) : ?>
						<div class="option_holder <?php echo $i%2 == 0 ? 'left' : 'right'; ?><?php if($option->hasLabel()) echo ' has_label'; ?>">
							<h4><?php Text::underscoreToWord($option->getName()) ?></h4>
							<?php if($option->hasLabel()) : ?>
								<h5><?php echo $option->getLabel(); ?></h5>
							<?php endif; ?>
							<?php FormElement::render($option); $i++; ?>
              <span class="default_value"><?php echo $option->getDefault(); ?></span>
						</div>
					<?php endforeach; ?>
				</div>
			</div>
		<?php $t++; endforeach; ?>
		<input type="submit" class="button submit" name="responsive_menu_submit" value="Update Options" />
	</form>
</div>
