<?php

$default_options = array(

	'breakpoint' => 800,
	'menu_to_hide' => '',
	'menu_depth' => 2,
	'menu_to_use' => '',
  'theme_location_menu' => '',

  // Button Settings
  'button_title' => null,
  'button_image' => null,
  'button_image_when_clicked' => null,
  'button_font_icon' => null,
  'button_font_icon_when_clicked' => null,
  'button_click_trigger' => '#responsive-menu-button',
  'button_title_position' => 'left',
  'button_title_line_height' => '13',
  'button_background_colour' => '#000',
  'button_click_animation' => 'boring',
  'button_line_colour' => '#fff',
  'button_text_colour' => '#fff',
  'button_transparent_background' => 'off',
  'button_width' => 50,
  'button_height' => 50,
  'button_line_margin' => 5,
  'button_line_height' => 3,
  'button_line_width' => 25,
  'button_top' => 50,
  'button_distance_from_side' => 5,
  'button_left_or_right' => 'right',
  'button_position_type' => 'absolute',
  'button_push_with_animation' => 'off',
  'button_font_size' => 14,

  // Animation Settings
  'animation_type' => 'slide',
  'page_wrapper' => null,
  'animation_speed' => 0.5,
  'transition_speed' => 0.5,

  // Menu Settings
  'active_arrow_shape' => '▲',
  'inactive_arrow_shape' => '▼',
  'active_arrow_image' => '',
  'inactive_arrow_image' => '',
  'active_arrow_font_icon' => '',
  'inactive_arrow_font_icon' => '',
  'accordion_animation' => 'off',
  'auto_expand_all_submenus' => 'off',
  'auto_expand_current_submenus' => 'off',

  'menu_background_colour' => '#fff',
  'menu_item_background_colour' => '#fff',
  'menu_item_background_hover_colour' => '#fff',
  'menu_item_border_colour' => '#fff',
  'menu_title_background_colour' => '#fff',
  'menu_title_background_hover_colour' => '#fff',
  'menu_current_item_background_colour' => '#fff',
  'menu_current_item_background_hover_colour' => '#fff',
  'menu_title_colour' => '#fff',
  'menu_title_hover_colour' => '#fff',
  'menu_link_colour' => '#fff',
  'menu_link_hover_colour' => '#fff',
  'menu_current_link_colour' => '#fff',
  'menu_current_link_hover_colour' => '#fff',
  'menu_sub_arrow_border_colour' => '#fff',
  'menu_sub_arrow_border_hover_colour' => '#fff',
  'menu_sub_arrow_background_colour' => '#fff',
  'menu_sub_arrow_background_hover_colour' => '#fff',
  'menu_sub_arrow_shape_colour' => '#fff',
  'menu_sub_arrow_shape_hover_colour' => '#fff',
  'menu_font' => null,
  'menu_font_size' => 13,
  'menu_title_font_size' => 13,
  'menu_text_alignment' => 'left',
  'menu_links_height' => 20,
  'menu_minimum_width' => null,
  'menu_maximum_width' => null,
  'menu_auto_height' => 'off',
  'menu_additional_content' => null,
  'menu_additional_content_position' => 'above',
  'menu_title' => null,
  'menu_title_image' => null,
  'menu_title_font_icon' => null,
  'menu_appear_from' => 'left',
  'menu_title_link' => null,
  'menu_title_link_location' => '_self',
  'menu_width' => 75,
  'menu_close_on_link_click' => 'off',
  'menu_item_click_to_trigger_submenu' => 'off',
  'menu_disable_scrolling' => 'off',
  'menu_overlay' => 'off',
  'menu_overlay_colour' => 'rgba(0,0,0,0.7)',
  'menu_font_icons' => '',
  'menu_remove_search_box' => 'off',
  'menu_search_box_text' => 'Search',
  'menu_word_wrap' => 'off',

  'minify_scripts' => 'off',
  'scripts_in_footer' => 'off',
  'external_files' => 'off',

  'shortcode' => 'off',
  'mobile_only' => 'off',
  'custom_walker' => null,
  'custom_css' => null,

  'use_single_menu' => 'off',
  'single_menu_height' => '80',
  'single_menu_item_link_colour' => '#ffffff',
  'single_menu_item_hover_colour' => '#ffffff',

  'use_header_bar' => 'off',
  'header_bar_logo' => null,
  'header_bar_logo_link' => null,
  'header_bar_html_content' => null,
  'header_bar_height' => '80',
  'header_bar_background_color' => '#ffffff',
  'header_include_search_bar' => 'off',

  'items_order' => '{"menu":"","search":"","additional content":""}'

);
