<?php

$default_options = array(

	'breakpoint' => 800,
	'menu_to_hide' => '',
	'depth' => 2,
	'transient_caching' => 'off',
	'menu_to_use' => '',
  'theme_location_menu' => '',

  // Button Settings
  'button_title' => null,
  'button_image' => null,
  'button_x_on_click' => 'off',
  'button_image_when_clicked' => null,
  'button_click_trigger' => '#responsive_menu_button',
  'button_title_position' => 'left',
  'button_title_line_height' => '13',
  'button_background_colour' => '#000',
  'button_click_animation' => 'elastic',
  'button_line_colour' => '#fff',
  'button_text_colour' => '#fff',
  'button_transparent_background' => 'off',
  'button_width' => 50,
  'button_height' => 50,
  'button_line_margin' => 5,
  'button_line_height' => 3,
  'button_line_width' => 25,
  'button_top' => 50,
  'button_distance_from_side' => 5,
  'button_left_or_right' => 'right',
  'button_position_type' => 'absolute',
  'button_push_with_animation' => 'off',
  'button_font_size' => 13,

  // Animation Settings
  'animation_type' => 'slide',
  'page_wrapper' => null,
  'animation_speed' => 0.5,
  'transition_speed' => 1,

  // Menu Settings
  'accordion_animation' => 'off',
  'active_arrow_shape' => '▲',
  'inactive_arrow_shape' => '▼',
  'active_arrow_image' => '',
  'inactive_arrow_image' => '',
  'menu_item_background_colour' => '#fff',
  'menu_item_background_hover_colour' => '#fff',
  'menu_item_border_colour' => '#fff',
  'menu_title_background_colour' => '#fff',
  'menu_current_item_background_colour' => '#fff',
  'menu_current_item_background_hover_colour' => '#fff',
  'menu_title_colour' => '#fff',
  'menu_title_hover_colour' => '#fff',
  'menu_link_colour' => '#fff',
  'menu_link_hover_colour' => '#fff',
  'menu_current_link_colour' => '#fff',
  'menu_current_link_hover_colour' => '#fff',
  'menu_font' => null,
  'menu_font_size' => 13,
  'menu_title_font_size' => 13,
  'menu_text_alignment' => 'left',
  'menu_links_height' => 20,
  'menu_minimum_width' => null,
  'menu_maximum_width' => null,
  'menu_auto_height' => 'off',
  'menu_additional_content' => null,
  'menu_additional_content_position' => 'above',
  'menu_title' => null,
  'menu_title_image' => null,
  'menu_slide_side' => 'left',
  'menu_title_link' => null,
  'menu_title_link_location' => '_self',
  'menu_width' => 75,

  'minify_scripts' => 'off',
  'scripts_in_footer' => 'off',
  'external_files' => 'off',
  'remove_important_tags' => 'off',

  'shortcode' => 'off',
  'mobile_only' => 'off'
);
