/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n';
import { applyFilters } from '@wordpress/hooks';
import {
	addCard,
	addSubmenu,
	alignCenter,
	alignJustify,
	alignLeft,
	alignNone,
	alignRight,
	archive,
	arrowDown,
	arrowLeft,
	arrowRight,
	arrowUp,
	atSymbol,
	aspectRatio,
	audio,
	backup,
	blockDefault,
	blockTable,
	box,
	brush,
	bug,
	button,
	buttons,
	calendar,
	cancelCircleFilled,
	capturePhoto,
	captureVideo,
	category,
	chartBar,
	check,
	chevronDown,
	chevronLeft,
	chevronRight,
	chevronRightSmall,
	chevronUp,
	classic,
	close,
	closeSmall,
	cloudUpload,
	cloud,
	code,
	cog,
	color,
	column,
	columns,
	comment,
	commentAuthorAvatar,
	commentAuthorName,
	commentContent,
	// commentEditLink, the WP Icons NPM package does not yet include this icon.
	commentReplyLink,
	cover,
	create,
	crop,
	currencyDollar,
	currencyEuro,
	currencyPound,
	customPostType,
	desktop,
	dragHandle,
	download,
	edit,
	external,
	file,
	flipHorizontal,
	flipVertical,
	formatBold,
	formatCapitalize,
	formatIndent,
	formatIndentRTL,
	formatItalic,
	formatListBullets,
	formatListBulletsRTL,
	formatListNumbered,
	formatListNumberedRTL,
	formatLtr,
	formatLowercase,
	formatOutdent,
	formatOutdentRTL,
	formatRtl,
	formatStrikethrough,
	formatUnderline,
	formatUppercase,
	fullscreen,
	gallery,
	globe,
	grid,
	group,
	handle,
	heading,
	help,
	helpFilled,
	inbox,
	institution,
	home,
	html,
	image,
	info,
	insertAfter,
	insertBefore,
	justifyLeft,
	justifyCenter,
	justifyRight,
	justifySpaceBetween,
	key,
	keyboardClose,
	keyboardReturn,
	layout,
	lifesaver,
	// There are some issues with these icons.
	// lineDashed,
	// lineDotted,
	// lineSolid,
	link,
	linkOff,
	list,
	listView,
	lock,
	login,
	loop,
	mapMarker,
	media,
	mediaAndText,
	megaphone,
	menu,
	mobile,
	more,
	moreHorizontal,
	moreHorizontalMobile,
	moreVertical,
	moveTo,
	navigation,
	overlayText,
	pageBreak,
	customLink,
	page,
	pages,
	paragraph,
	payment,
	percent,
	positionCenter,
	positionLeft,
	positionRight,
	pencil,
	people,
	pin,
	plugins,
	plusCircleFilled,
	plusCircle,
	plus,
	post,
	postAuthor,
	postCategories,
	postContent,
	postComments,
	postCommentsCount,
	postCommentsForm,
	postDate,
	postExcerpt,
	postFeaturedImage,
	postList,
	postTerms,
	previous,
	next,
	preformatted,
	pullLeft,
	pullRight,
	pullquote,
	queryPagination,
	queryPaginationNext,
	queryPaginationNumbers,
	queryPaginationPrevious,
	quote,
	receipt,
	redo,
	removeBug,
	removeSubmenu,
	replace,
	reset,
	resizeCornerNE,
	reusableBlock,
	rotateLeft,
	rotateRight,
	row,
	rss,
	search,
	separator,
	settings,
	share,
	shield,
	shortcode,
	siteLogo,
	stack,
	starEmpty,
	starFilled,
	starHalf,
	store,
	stretchFullWidth,
	styles,
	shipping,
	stretchWide,
	subscript,
	superscript,
	swatch,
	symbol,
	symbolFilled,
	tableColumnAfter,
	tableColumnBefore,
	tableColumnDelete,
	tableRowAfter,
	tableRowBefore,
	tableRowDelete,
	table,
	tag,
	termDescription,
	footer,
	header,
	sidebar,
	textColor,
	tablet,
	tip,
	title,
	tool,
	trash,
	trendingDown,
	trendingUp,
	typography,
	undo,
	ungroup,
	unlock,
	update,
	upload,
	verse,
	video,
	warning,
	widget,
} from '@wordpress/icons';

/**
 * Internal dependencies
 */
import {
	amazon,
	bandcamp,
	behance,
	chain,
	codepen,
	deviantart,
	dribbble,
	dropbox,
	etsy,
	facebook,
	feed,
	fivehundredpx,
	flickr,
	foursquare,
	goodreads,
	google,
	github,
	instagram,
	lastfm,
	linkedin,
	mail,
	mastodon,
	meetup,
	medium,
	patreon,
	pinterest,
	pocket,
	redditSolid,
	reddit,
	skype,
	snapchat,
	soundcloud,
	spotify,
	telegram,
	tiktok,
	tumblr,
	twitch,
	twitter,
	twitterx,
	vimeo,
	vk,
	wordpress,
	yelp,
	youtube,
} from './wordpress/social';

// Temporary icon specifications that are not yet in the NPM package.
import { commentEditLink, sparkles } from './wordpress/temp';

const wordpressSocialIcons = [
	{
		isDefault: true,
		name: 'wordpress',
		title: 'WordPress',
		icon: wordpress,
		categories: ['logos'],
	},
	{
		name: 'fivehundredpx',
		title: '500px',
		icon: fivehundredpx,
		categories: ['logos'],
	},
	{
		name: 'amazon',
		title: 'Amazon',
		icon: amazon,
		categories: ['logos'],
	},
	{
		name: 'bandcamp',
		title: 'Bandcamp',
		icon: bandcamp,
		categories: ['logos'],
	},
	{
		name: 'behance',
		title: 'Behance',
		icon: behance,
		categories: ['logos'],
	},
	{
		name: 'chain',
		title: 'Link',
		icon: chain,
	},
	{
		name: 'codepen',
		title: 'CodePen',
		icon: codepen,
		categories: ['logos'],
	},
	{
		name: 'deviantart',
		title: 'DeviantArt',
		icon: deviantart,
		categories: ['logos'],
	},
	{
		name: 'dribbble',
		title: 'Dribbble',
		icon: dribbble,
		categories: ['logos'],
	},
	{
		name: 'dropbox',
		title: 'Dropbox',
		icon: dropbox,
		categories: ['logos'],
	},
	{
		name: 'etsy',
		title: 'Etsy',
		icon: etsy,
		categories: ['logos'],
	},
	{
		name: 'facebook',
		title: 'Facebook',
		icon: facebook,
		categories: ['logos'],
	},
	{
		name: 'feed',
		title: 'RSS Feed',
		icon: feed,
		categories: ['logos'],
	},
	{
		name: 'flickr',
		title: 'Flickr',
		icon: flickr,
		categories: ['logos'],
	},
	{
		name: 'foursquare',
		title: 'Foursquare',
		icon: foursquare,
		categories: ['logos'],
	},
	{
		name: 'goodreads',
		title: 'Goodreads',
		icon: goodreads,
		categories: ['logos'],
	},
	{
		name: 'google',
		title: 'Google',
		icon: google,
		categories: ['logos'],
	},
	{
		name: 'github',
		title: 'GitHub',
		icon: github,
		categories: ['logos'],
	},
	{
		name: 'instagram',
		title: 'Instagram',
		icon: instagram,
		categories: ['logos'],
	},
	{
		name: 'lastfm',
		title: 'Last.fm',
		icon: lastfm,
		categories: ['logos'],
	},
	{
		name: 'linkedin',
		title: 'LinkedIn',
		icon: linkedin,
		categories: ['logos'],
	},
	{
		name: 'mail',
		title: 'Mail',
		keywords: ['email', 'e-mail'],
		icon: mail,
	},
	{
		name: 'mastodon',
		title: 'Mastodon',
		icon: mastodon,
		categories: ['logos'],
	},
	{
		name: 'meetup',
		title: 'Meetup',
		icon: meetup,
		categories: ['logos'],
	},
	{
		name: 'medium',
		title: 'Medium',
		icon: medium,
		categories: ['logos'],
	},
	{
		name: 'patreon',
		title: 'Patreon',
		icon: patreon,
		categories: ['logos'],
	},
	{
		name: 'pinterest',
		title: 'Pinterest',
		icon: pinterest,
		categories: ['logos'],
	},
	{
		name: 'pocket',
		title: 'Pocket',
		icon: pocket,
		categories: ['logos'],
	},
	{
		name: 'reddit-solid',
		title: 'Reddit Solid',
		icon: redditSolid,
		categories: ['logos'],
	},
	{
		name: 'reddit',
		title: 'Reddit',
		icon: reddit,
		categories: ['logos'],
	},
	{
		name: 'skype',
		title: 'Skype',
		icon: skype,
		categories: ['logos'],
	},
	{
		name: 'snapchat',
		title: 'Snapchat',
		icon: snapchat,
		categories: ['logos'],
	},
	{
		name: 'soundcloud',
		title: 'SoundCloud',
		icon: soundcloud,
		categories: ['logos'],
	},
	{
		name: 'spotify',
		title: 'Spotify',
		icon: spotify,
		categories: ['logos'],
	},
	{
		name: 'telegram',
		title: 'Telegram',
		icon: telegram,
		categories: ['logos'],
	},
	{
		name: 'tiktok',
		title: 'TikTok',
		icon: tiktok,
		categories: ['logos'],
	},
	{
		name: 'tumblr',
		title: 'Tumblr',
		icon: tumblr,
		categories: ['logos'],
	},
	{
		name: 'twitch',
		title: 'Twitch',
		icon: twitch,
		categories: ['logos'],
	},
	{
		isDefault: true,
		name: 'twitter',
		title: 'Twitter',
		icon: twitter,
		categories: ['logos'],
	},
	{
		isDefault: true,
		name: 'twitterx',
		title: 'Twitter X',
		icon: twitterx,
		categories: ['logos'],
	},
	{
		name: 'vimeo',
		title: 'Vimeo',
		icon: vimeo,
		categories: ['logos'],
	},
	{
		name: 'vk',
		title: 'VK',
		icon: vk,
		categories: ['logos'],
	},
	{
		name: 'yelp',
		title: 'Yelp',
		icon: yelp,
		categories: ['logos'],
	},
	{
		name: 'youtube',
		title: 'YouTube',
		icon: youtube,
		categories: ['logos'],
	},
];

const wordpressIcons = [
	{
		name: 'addCard',
		title: __('Add Card', 'responsive-menu'),
		icon: addCard,
	},
	{
		name: 'addSubmenu',
		title: __('Add Submenu', 'responsive-menu'),
		icon: addSubmenu,
		categories: ['arrows'],
	},
	{
		name: 'alignCenter',
		title: __('Align Center', 'responsive-menu'),
		icon: alignCenter,
		categories: ['editor'],
	},
	{
		name: 'alignJustify',
		title: __('Align Justify', 'responsive-menu'),
		icon: alignJustify,
		categories: ['editor'],
	},
	{
		name: 'alignLeft',
		title: __('Align Left', 'responsive-menu'),
		icon: alignLeft,
		categories: ['editor'],
	},
	{
		name: 'alignNone',
		title: __('Align None', 'responsive-menu'),
		icon: alignNone,
		categories: ['editor'],
	},
	{
		name: 'alignRight',
		title: __('Align Right', 'responsive-menu'),
		icon: alignRight,
		categories: ['editor'],
	},
	{
		name: 'archive',
		title: __('Archive', 'responsive-menu'),
		icon: archive,
		categories: ['blocks'],
	},
	{
		name: 'arrowDown',
		title: __('Arrow Down', 'responsive-menu'),
		icon: arrowDown,
		categories: ['arrows'],
	},
	{
		name: 'arrowLeft',
		title: __('Arrow Left', 'responsive-menu'),
		icon: arrowLeft,
		categories: ['arrows'],
	},
	{
		name: 'arrowRight',
		title: __('Arrow Right', 'responsive-menu'),
		icon: arrowRight,
		categories: ['arrows'],
	},
	{
		name: 'arrowUp',
		title: __('Arrow Up', 'responsive-menu'),
		icon: arrowUp,
		categories: ['arrows'],
	},
	{
		name: 'atSymbol',
		title: __('At Symbol', 'responsive-menu'),
		icon: atSymbol,
	},
	{
		name: 'aspectRatio',
		title: __('Aspect Ratio', 'responsive-menu'),
		icon: aspectRatio,
		categories: ['media'],
	},
	{
		name: 'audio',
		title: __('Audio', 'responsive-menu'),
		icon: audio,
		categories: ['media'],
	},
	{
		name: 'backup',
		title: __('Backup', 'responsive-menu'),
		icon: backup,
	},
	{
		name: 'blockDefault',
		title: __('Block Default', 'responsive-menu'),
		icon: blockDefault,
		categories: ['blocks'],
	},
	{
		name: 'blockTable',
		title: __('Block Table', 'responsive-menu'),
		icon: blockTable,
	},
	{
		name: 'box',
		title: __('Box', 'responsive-menu'),
		icon: box,
	},
	{
		name: 'brush',
		title: __('Brush', 'responsive-menu'),
		icon: brush,
	},
	{
		name: 'bug',
		title: __('Bug', 'responsive-menu'),
		icon: bug,
	},
	{
		name: 'button',
		title: __('Button', 'responsive-menu'),
		icon: button,
		categories: ['blocks'],
	},
	{
		name: 'buttons',
		title: __('Buttons', 'responsive-menu'),
		icon: buttons,
		categories: ['blocks'],
	},
	{
		name: 'calendar',
		title: __('Calendar', 'responsive-menu'),
		icon: calendar,
		categories: ['blocks'],
	},
	{
		name: 'cancelCircleFilled',
		title: __('Cancel - Circle Filled', 'responsive-menu'),
		icon: cancelCircleFilled,
	},
	{
		name: 'capturePhoto',
		title: __('Capture Photo', 'responsive-menu'),
		icon: capturePhoto,
		categories: ['media'],
	},
	{
		name: 'captureVideo',
		title: __('Capture Video', 'responsive-menu'),
		icon: captureVideo,
		categories: ['media'],
	},
	{
		name: 'category',
		title: __('Category', 'responsive-menu'),
		icon: category,
		categories: ['blocks'],
	},
	{
		name: 'chartBar',
		title: __('Chart Bar', 'responsive-menu'),
		icon: chartBar,
	},
	{
		name: 'check',
		title: __('Check', 'responsive-menu'),
		icon: check,
	},
	{
		name: 'chevronDown',
		title: __('Chevron Down', 'responsive-menu'),
		icon: chevronDown,
		categories: ['arrows'],
	},
	{
		name: 'chevronLeft',
		title: __('Chevron Left', 'responsive-menu'),
		icon: chevronLeft,
		categories: ['arrows'],
	},
	{
		name: 'chevronRight',
		title: __('Chevron Right', 'responsive-menu'),
		icon: chevronRight,
		categories: ['arrows'],
	},
	{
		name: 'chevronRightSmall',
		title: __('Chevron Right - Small', 'responsive-menu'),
		icon: chevronRightSmall,
		categories: ['arrows'],
	},
	{
		name: 'chevronUp',
		title: __('Chevron Up', 'responsive-menu'),
		icon: chevronUp,
		categories: ['arrows'],
	},
	{
		name: 'classic',
		title: __('Classic', 'responsive-menu'),
		icon: classic,
		categories: ['blocks'],
	},
	{
		name: 'close',
		title: __('Close', 'responsive-menu'),
		icon: close,
	},
	{
		name: 'closeSmall',
		title: __('Close - Small', 'responsive-menu'),
		icon: closeSmall,
	},
	{
		name: 'cloudUpload',
		title: __('Cloud Upload', 'responsive-menu'),
		icon: cloudUpload,
		categories: ['arrows'],
	},
	{
		name: 'cloud',
		title: __('Cloud', 'responsive-menu'),
		icon: cloud,
	},
	{
		name: 'code',
		title: __('Code', 'responsive-menu'),
		icon: code,
		categories: ['blocks'],
	},
	{
		name: 'cog',
		title: __('Cog', 'responsive-menu'),
		icon: cog,
	},
	{
		name: 'color',
		title: __('Color', 'responsive-menu'),
		icon: color,
	},
	{
		name: 'column',
		title: __('Column', 'responsive-menu'),
		icon: column,
		categories: ['blocks'],
	},
	{
		name: 'columns',
		title: __('Columns', 'responsive-menu'),
		icon: columns,
		categories: ['blocks'],
	},
	{
		name: 'comment',
		title: __('Comment', 'responsive-menu'),
		icon: comment,
		categories: ['blocks'],
	},
	{
		name: 'commentAuthorAvatar',
		title: __('Comment Author Avatar', 'responsive-menu'),
		icon: commentAuthorAvatar,
		categories: ['blocks'],
	},
	{
		name: 'commentAuthorName',
		title: __('Comment Author Name', 'responsive-menu'),
		icon: commentAuthorName,
		categories: ['blocks'],
	},
	{
		name: 'commentContent',
		title: __('Comment Content', 'responsive-menu'),
		icon: commentContent,
		categories: ['blocks'],
	},
	{
		name: 'commentEditLink',
		title: __('Comment Edit Link', 'responsive-menu'),
		icon: commentEditLink,
		categories: ['blocks'],
	},
	{
		name: 'commentReplyLink',
		title: __('Comment Reply Link', 'responsive-menu'),
		icon: commentReplyLink,
		categories: ['blocks'],
	},
	{
		name: 'cover',
		title: __('Cover', 'responsive-menu'),
		icon: cover,
		categories: ['blocks'],
	},
	{
		name: 'create',
		title: __('Create', 'responsive-menu'),
		icon: create,
	},
	{
		name: 'crop',
		title: __('Crop', 'responsive-menu'),
		icon: crop,
	},
	{
		name: 'currencyDollar',
		title: __('Currency Dollar', 'responsive-menu'),
		icon: currencyDollar,
	},
	{
		name: 'currencyEuro',
		title: __('Currency Euro', 'responsive-menu'),
		icon: currencyEuro,
	},
	{
		name: 'currencyPound',
		title: __('Currency Pound', 'responsive-menu'),
		icon: currencyPound,
	},
	{
		name: 'customPostType',
		title: __('Custom Post Type', 'responsive-menu'),
		icon: customPostType,
	},
	{
		name: 'desktop',
		title: __('Desktop', 'responsive-menu'),
		icon: desktop,
		categories: ['devices'],
	},
	{
		name: 'dragHandle',
		title: __('Drag Handle', 'responsive-menu'),
		icon: dragHandle,
	},
	{
		name: 'download',
		title: __('Download', 'responsive-menu'),
		icon: download,
		categories: ['arrows'],
	},
	{
		name: 'edit',
		title: __('Edit', 'responsive-menu'),
		icon: edit,
	},
	{
		name: 'external',
		title: __('External', 'responsive-menu'),
		icon: external,
	},
	{
		name: 'file',
		title: __('File', 'responsive-menu'),
		icon: file,
	},
	{
		name: 'flipHorizontal',
		title: __('Flip Horizontal', 'responsive-menu'),
		icon: flipHorizontal,
	},
	{
		name: 'flipVertical',
		title: __('Flip Vertical', 'responsive-menu'),
		icon: flipVertical,
	},
	{
		name: 'formatBold',
		title: __('Format Bold', 'responsive-menu'),
		icon: formatBold,
		categories: ['editor'],
	},
	{
		name: 'formatCapitalize',
		title: __('Format Capitalize', 'responsive-menu'),
		icon: formatCapitalize,
		categories: ['editor'],
	},
	{
		name: 'formatIndent',
		title: __('Format Indent', 'responsive-menu'),
		icon: formatIndent,
		categories: ['editor'],
	},
	{
		name: 'formatIndentRTL',
		title: __('Format Indent RTL', 'responsive-menu'),
		icon: formatIndentRTL,
	},
	{
		name: 'formatItalic',
		title: __('Format Italic', 'responsive-menu'),
		icon: formatItalic,
		categories: ['editor'],
	},
	{
		name: 'formatListBullets',
		title: __('Format List Bullets', 'responsive-menu'),
		icon: formatListBullets,
		categories: ['editor'],
	},
	{
		name: 'formatListBulletsRTL',
		title: __('Format List Bullets RTL', 'responsive-menu'),
		icon: formatListBulletsRTL,
		categories: ['editor'],
	},
	{
		name: 'formatListNumbered',
		title: __('Format List Numbered', 'responsive-menu'),
		icon: formatListNumbered,
		categories: ['editor'],
	},
	{
		name: 'formatListNumberedRTL',
		title: __('Format List Numbered RTL', 'responsive-menu'),
		icon: formatListNumberedRTL,
		categories: ['editor'],
	},
	{
		name: 'formatLtr',
		title: __('Format LTR', 'responsive-menu'),
		icon: formatLtr,
		categories: ['editor'],
	},
	{
		name: 'formatLowercase',
		title: __('Format Lowercase', 'responsive-menu'),
		icon: formatLowercase,
		categories: ['editor'],
	},
	{
		name: 'formatOutdent',
		title: __('Format Outdent', 'responsive-menu'),
		icon: formatOutdent,
		categories: ['editor'],
	},
	{
		name: 'formatOutdentRTL',
		title: __('Format Outdent RTL', 'responsive-menu'),
		icon: formatOutdentRTL,
		categories: ['editor'],
	},
	{
		name: 'formatRtl',
		title: __('Format RTL', 'responsive-menu'),
		icon: formatRtl,
		categories: ['editor'],
	},
	{
		name: 'formatStrikethrough',
		title: __('Format Strikethrough', 'responsive-menu'),
		icon: formatStrikethrough,
		categories: ['editor'],
	},
	{
		name: 'formatUnderline',
		title: __('Format Underline', 'responsive-menu'),
		icon: formatUnderline,
		categories: ['editor'],
	},
	{
		name: 'formatUppercase',
		title: __('Format Uppercase', 'responsive-menu'),
		icon: formatUppercase,
		categories: ['editor'],
	},
	{
		name: 'fullscreen',
		title: __('Fullscreen', 'responsive-menu'),
		icon: fullscreen,
		categories: ['editor'],
	},
	{
		name: 'gallery',
		title: __('Gallery', 'responsive-menu'),
		icon: gallery,
		categories: ['blocks', 'media'],
	},
	{
		name: 'globe',
		title: __('Globe', 'responsive-menu'),
		icon: globe,
	},
	{
		name: 'grid',
		title: __('Grid', 'responsive-menu'),
		icon: grid,
	},
	{
		name: 'group',
		title: __('Group', 'responsive-menu'),
		icon: group,
		categories: ['blocks'],
	},
	{
		name: 'handle',
		title: __('Handle', 'responsive-menu'),
		icon: handle,
	},
	{
		name: 'heading',
		title: __('Heading', 'responsive-menu'),
		icon: heading,
		categories: ['blocks'],
	},
	{
		name: 'help',
		title: __('Help', 'responsive-menu'),
		icon: help,
	},
	{
		name: 'helpFilled',
		title: __('Help - Filled', 'responsive-menu'),
		icon: helpFilled,
	},
	{
		name: 'inbox',
		title: __('Inbox', 'responsive-menu'),
		icon: inbox,
	},
	{
		name: 'institution',
		title: __('Institution', 'responsive-menu'),
		icon: institution,
	},
	{
		name: 'home',
		title: __('Home', 'responsive-menu'),
		icon: home,
		categories: ['blocks'],
	},
	{
		name: 'html',
		title: __('HTML', 'responsive-menu'),
		icon: html,
		categories: ['blocks'],
	},
	{
		isDefault: true,
		name: 'image',
		title: __('Image', 'responsive-menu'),
		icon: image,
		categories: ['blocks', 'media'],
	},
	{
		name: 'info',
		title: __('Info', 'responsive-menu'),
		icon: info,
	},
	{
		name: 'insertAfter',
		title: __('Insert After', 'responsive-menu'),
		icon: insertAfter,
		categories: ['editor'],
	},
	{
		name: 'insertBefore',
		title: __('Insert Before', 'responsive-menu'),
		icon: insertBefore,
		categories: ['editor'],
	},
	{
		name: 'justifyLeft',
		title: __('Justify Left', 'responsive-menu'),
		icon: justifyLeft,
		categories: ['editor'],
	},
	{
		name: 'justifyCenter',
		title: __('Justify Center', 'responsive-menu'),
		icon: justifyCenter,
		categories: ['editor'],
	},
	{
		name: 'justifyRight',
		title: __('Justify Right', 'responsive-menu'),
		icon: justifyRight,
		categories: ['editor'],
	},
	{
		name: 'justifySpaceBetween',
		title: __('Justify Space Between', 'responsive-menu'),
		icon: justifySpaceBetween,
		categories: ['editor'],
	},
	{
		name: 'key',
		title: __('Key', 'responsive-menu'),
		icon: key,
	},
	{
		name: 'keyboardClose',
		title: __('Keyboard Close', 'responsive-menu'),
		icon: keyboardClose,
		categories: ['editor'],
	},
	{
		name: 'keyboardReturn',
		title: __('Keyboard Return', 'responsive-menu'),
		icon: keyboardReturn,
		categories: ['editor'],
	},
	{
		name: 'layout',
		title: __('Layout', 'responsive-menu'),
		icon: layout,
	},
	{
		name: 'lifesaver',
		title: __('Lifesaver', 'responsive-menu'),
		icon: lifesaver,
	},
	// There are some issues with these icons.
	// {
	// 	name: 'lineDashed',
	// 	title:  __( 'Line Dashed', 'responsive-menu' ),
	// 	icon: lineDashed,
	// },
	// {
	// 	name: 'lineDotted',
	// 	title:  __( 'Line Dotted', 'responsive-menu' ),
	// 	icon: lineDotted,
	// },
	// {
	// 	name: 'lineSolid',
	// 	title:  __( 'Line Solid', 'responsive-menu' ),
	// 	icon: lineSolid,
	// },
	{
		name: 'link',
		title: __('Link', 'responsive-menu'),
		icon: link,
		categories: ['editor'],
	},
	{
		name: 'linkOff',
		title: __('Link Off', 'responsive-menu'),
		icon: linkOff,
		categories: ['editor'],
	},
	{
		name: 'list',
		title: __('List', 'responsive-menu'),
		icon: list,
		categories: ['blocks'],
	},
	{
		name: 'listView',
		title: __('List View', 'responsive-menu'),
		icon: listView,
		categories: ['editor'],
	},
	{
		name: 'lock',
		title: __('Lock', 'responsive-menu'),
		icon: lock,
		categories: ['editor'],
	},
	{
		name: 'login',
		title: __('Login', 'responsive-menu'),
		icon: login,
	},
	{
		name: 'loop',
		title: __('Loop', 'responsive-menu'),
		icon: loop,
		categories: ['blocks'],
	},
	{
		name: 'mapMarker',
		title: __('Map Marker', 'responsive-menu'),
		icon: mapMarker,
	},
	{
		name: 'media',
		title: __('Media', 'responsive-menu'),
		icon: media,
		categories: ['blocks', 'media'],
	},
	{
		name: 'mediaAndText',
		title: __('Media & Text', 'responsive-menu'),
		icon: mediaAndText,
		categories: ['blocks', 'media'],
	},
	{
		name: 'megaphone',
		title: __('Megaphone', 'responsive-menu'),
		icon: megaphone,
	},
	{
		name: 'menu',
		title: __('Menu', 'responsive-menu'),
		icon: menu,
	},
	{
		name: 'mobile',
		title: __('Mobile', 'responsive-menu'),
		icon: mobile,
		categories: ['devices'],
	},
	{
		name: 'more',
		title: __('More', 'responsive-menu'),
		icon: more,
	},
	{
		name: 'moreHorizontal',
		title: __('More Horizontal', 'responsive-menu'),
		icon: moreHorizontal,
	},
	{
		name: 'moreHorizontalMobile',
		title: __('More Horizontal - Mobile', 'responsive-menu'),
		icon: moreHorizontalMobile,
	},
	{
		name: 'moreVertical',
		title: __('More Vertical', 'responsive-menu'),
		icon: moreVertical,
	},
	{
		name: 'moveTo',
		title: __('Move To', 'responsive-menu'),
		icon: moveTo,
		categories: ['arrows'],
	},
	{
		name: 'navigation',
		title: __('Navigation', 'responsive-menu'),
		icon: navigation,
	},
	{
		name: 'overlayText',
		title: __('Overlay Text', 'responsive-menu'),
		icon: overlayText,
	},
	{
		name: 'pageBreak',
		title: __('Page Break', 'responsive-menu'),
		icon: pageBreak,
	},
	{
		name: 'customLink',
		title: __('Custom Link', 'responsive-menu'),
		icon: customLink,
	},
	{
		name: 'page',
		title: __('Page', 'responsive-menu'),
		icon: page,
	},
	{
		name: 'pages',
		title: __('Pages', 'responsive-menu'),
		icon: pages,
	},
	{
		name: 'paragraph',
		title: __('Paragraph', 'responsive-menu'),
		icon: paragraph,
	},
	{
		name: 'payment',
		title: __('Payment', 'responsive-menu'),
		icon: payment,
	},
	{
		name: 'percent',
		title: __('Percent', 'responsive-menu'),
		icon: percent,
	},
	{
		name: 'positionCenter',
		title: __('Position Center', 'responsive-menu'),
		icon: positionCenter,
	},
	{
		name: 'positionLeft',
		title: __('Position Left', 'responsive-menu'),
		icon: positionLeft,
	},
	{
		name: 'positionRight',
		title: __('Position Right', 'responsive-menu'),
		icon: positionRight,
	},
	{
		name: 'post',
		title: __('Post', 'responsive-menu'),
		icon: post,
	},
	{
		name: 'pencil',
		title: __('Pencil', 'responsive-menu'),
		icon: pencil,
	},
	{
		name: 'people',
		title: __('People', 'responsive-menu'),
		icon: people,
	},
	{
		name: 'pin',
		title: __('Pin', 'responsive-menu'),
		icon: pin,
	},
	{
		name: 'plugins',
		title: __('Plugins', 'responsive-menu'),
		icon: plugins,
	},
	{
		name: 'plusCircleFilled',
		title: __('Plus Circle - Filled', 'responsive-menu'),
		icon: plusCircleFilled,
	},
	{
		name: 'plusCircle',
		title: __('Plus Circle', 'responsive-menu'),
		icon: plusCircle,
	},
	{
		name: 'plus',
		title: __('Plus', 'responsive-menu'),
		icon: plus,
	},
	{
		name: 'postAuthor',
		title: __('Post Author', 'responsive-menu'),
		icon: postAuthor,
		categories: ['blocks'],
	},
	{
		name: 'postCategories',
		title: __('Post Categories', 'responsive-menu'),
		icon: postCategories,
		categories: ['blocks'],
	},
	{
		name: 'postContent',
		title: __('Post Content', 'responsive-menu'),
		icon: postContent,
		categories: ['blocks'],
	},
	{
		name: 'postComments',
		title: __('Post Comments', 'responsive-menu'),
		icon: postComments,
		categories: ['blocks'],
	},
	{
		name: 'postCommentsCount',
		title: __('Post Comment Count', 'responsive-menu'),
		icon: postCommentsCount,
	},
	{
		name: 'postCommentsForm',
		title: __('Post Comments Form', 'responsive-menu'),
		icon: postCommentsForm,
		categories: ['blocks'],
	},
	{
		name: 'postDate',
		title: __('Post Date', 'responsive-menu'),
		icon: postDate,
		categories: ['blocks'],
	},
	{
		name: 'postExcerpt',
		title: __('Post Excerpt', 'responsive-menu'),
		icon: postExcerpt,
		categories: ['blocks'],
	},
	{
		name: 'postFeaturedImage',
		title: __('Post Featured Image', 'responsive-menu'),
		icon: postFeaturedImage,
		categories: ['blocks'],
	},
	{
		name: 'postList',
		title: __('Post List', 'responsive-menu'),
		icon: postList,
		categories: ['blocks'],
	},
	{
		name: 'postTerms',
		title: __('Post Terms', 'responsive-menu'),
		icon: postTerms,
		categories: ['blocks'],
	},
	{
		name: 'previous',
		title: __('Previous', 'responsive-menu'),
		icon: previous,
		categories: ['arrows'],
	},
	{
		name: 'next',
		title: __('Next', 'responsive-menu'),
		icon: next,
		categories: ['arrows'],
	},
	{
		name: 'preformatted',
		title: __('Preformatted', 'responsive-menu'),
		icon: preformatted,
	},
	{
		name: 'pullLeft',
		title: __('Pull Left', 'responsive-menu'),
		icon: pullLeft,
	},
	{
		name: 'pullRight',
		title: __('Pull Right', 'responsive-menu'),
		icon: pullRight,
	},
	{
		name: 'pullquote',
		title: __('Pull Quote', 'responsive-menu'),
		icon: pullquote,
	},
	{
		name: 'queryPagination',
		title: __('Query Pagination', 'responsive-menu'),
		icon: queryPagination,
	},
	{
		name: 'queryPaginationNext',
		title: __('Query Pagination Next', 'responsive-menu'),
		icon: queryPaginationNext,
		categories: ['arrows'],
	},
	{
		name: 'queryPaginationNumbers',
		title: __('Query Pagination Numbers', 'responsive-menu'),
		icon: queryPaginationNumbers,
	},
	{
		name: 'queryPaginationPrevious',
		title: __('Query Pagination Previous', 'responsive-menu'),
		icon: queryPaginationPrevious,
		categories: ['arrows'],
	},
	{
		name: 'quote',
		title: __('Quote', 'responsive-menu'),
		icon: quote,
		categories: ['blocks'],
	},
	{
		name: 'receipt',
		title: __('Receipt', 'responsive-menu'),
		icon: receipt,
	},
	{
		name: 'redo',
		title: __('Redo', 'responsive-menu'),
		icon: redo,
		categories: ['arrows', 'editor'],
	},
	{
		name: 'removeBug',
		title: __('Remove Bug', 'responsive-menu'),
		icon: removeBug,
	},
	{
		name: 'removeSubmenu',
		title: __('Remove Submenu', 'responsive-menu'),
		icon: removeSubmenu,
	},
	{
		name: 'replace',
		title: __('Replace', 'responsive-menu'),
		icon: replace,
		categories: ['arrows'],
	},
	{
		name: 'reset',
		title: __('Reset', 'responsive-menu'),
		icon: reset,
		keywords: ['minus'],
	},
	{
		name: 'resizeCornerNE',
		title: __('Resize Corner', 'responsive-menu'),
		icon: resizeCornerNE,
		categories: ['arrows'],
	},
	{
		name: 'reusableBlock',
		title: __('Reusable Block', 'responsive-menu'),
		icon: reusableBlock,
		categories: ['arrows'],
	},
	{
		name: 'rotateLeft',
		title: __('Rotate Left', 'responsive-menu'),
		icon: rotateLeft,
		categories: ['arrows'],
	},
	{
		name: 'rotateRight',
		title: __('Rotate Right', 'responsive-menu'),
		icon: rotateRight,
		categories: ['arrows'],
	},
	{
		name: 'row',
		title: __('Row', 'responsive-menu'),
		icon: row,
	},
	{
		name: 'rss',
		title: __('RSS', 'responsive-menu'),
		icon: rss,
	},
	{
		name: 'search',
		title: __('Search', 'responsive-menu'),
		icon: search,
		keywords: ['magnifying glass'],
	},
	{
		name: 'separator',
		title: __('Separator', 'responsive-menu'),
		icon: separator,
		categories: ['blocks'],
	},
	{
		name: 'settings',
		title: __('Settings', 'responsive-menu'),
		icon: settings,
	},
	{
		name: 'share',
		title: __('Share', 'responsive-menu'),
		icon: share,
	},
	{
		name: 'shield',
		title: __('Shield', 'responsive-menu'),
		icon: shield,
	},
	{
		name: 'shortcode',
		title: __('Shortcode', 'responsive-menu'),
		icon: shortcode,
		categories: ['blocks'],
	},
	{
		name: 'siteLogo',
		title: __('Site Logo', 'responsive-menu'),
		icon: siteLogo,
		categories: ['blocks', 'media'],
	},
	{
		isDefault: true,
		name: 'sparkles',
		title: __('Sparkles', 'responsive-menu'),
		icon: sparkles,
	},
	{
		name: 'stack',
		title: __('Stack', 'responsive-menu'),
		icon: stack,
	},
	{
		name: 'starEmpty',
		title: __('Star Empty', 'responsive-menu'),
		icon: starEmpty,
	},
	{
		name: 'starFilled',
		title: __('Star Filled', 'responsive-menu'),
		icon: starFilled,
	},
	{
		name: 'starHalf',
		title: __('Star Half', 'responsive-menu'),
		icon: starHalf,
	},
	{
		name: 'store',
		title: __('Store', 'responsive-menu'),
		icon: store,
	},
	{
		name: 'stretchFullWidth',
		title: __('Stretch Full Width', 'responsive-menu'),
		icon: stretchFullWidth,
		categories: ['editor'],
	},
	{
		name: 'styles',
		title: __('Styles', 'responsive-menu'),
		icon: styles,
	},
	{
		isDefault: true,
		name: 'shipping',
		title: __('Shipping', 'responsive-menu'),
		icon: shipping,
		keywords: ['truck'],
	},
	{
		name: 'stretchWide',
		title: __('Stretch Wide', 'responsive-menu'),
		icon: stretchWide,
		categories: ['editor'],
	},
	{
		name: 'subscript',
		title: __('Subscript', 'responsive-menu'),
		icon: subscript,
		categories: ['editor'],
	},
	{
		name: 'superscript',
		title: __('Superscript', 'responsive-menu'),
		icon: superscript,
		categories: ['editor'],
	},
	{
		name: 'swatch',
		title: __('Swatch', 'responsive-menu'),
		icon: swatch,
	},
	{
		name: 'symbol',
		title: __('Symbol', 'responsive-menu'),
		icon: symbol,
	},
	{
		name: 'symbolFilled',
		title: __('Symbol - Filled', 'responsive-menu'),
		icon: symbolFilled,
	},
	{
		name: 'tableColumnAfter',
		title: __('Table Column After', 'responsive-menu'),
		icon: tableColumnAfter,
		categories: ['editor'],
	},
	{
		name: 'tableColumnBefore',
		title: __('Table Column Before', 'responsive-menu'),
		icon: tableColumnBefore,
		categories: ['editor'],
	},
	{
		name: 'tableColumnDelete',
		title: __('Table Column Delete', 'responsive-menu'),
		icon: tableColumnDelete,
		categories: ['editor'],
	},
	{
		name: 'tableRowAfter',
		title: __('Table Row After', 'responsive-menu'),
		icon: tableRowAfter,
		categories: ['editor'],
	},
	{
		name: 'tableRowBefore',
		title: __('Table Row Before', 'responsive-menu'),
		icon: tableRowBefore,
		categories: ['editor'],
	},
	{
		name: 'tableRowDelete',
		title: __('Table Row Delete', 'responsive-menu'),
		icon: tableRowDelete,
		categories: ['editor'],
	},
	{
		name: 'table',
		title: __('Table', 'responsive-menu'),
		icon: table,
	},
	{
		name: 'tag',
		title: __('Tag', 'responsive-menu'),
		icon: tag,
	},
	{
		name: 'termDescription',
		title: __('Term Description', 'responsive-menu'),
		icon: termDescription,
		categories: ['blocks'],
	},
	{
		name: 'footer',
		title: __('Footer', 'responsive-menu'),
		icon: footer,
	},
	{
		name: 'header',
		title: __('Header', 'responsive-menu'),
		icon: header,
	},
	{
		name: 'sidebar',
		title: __('Sidebar', 'responsive-menu'),
		icon: sidebar,
	},
	{
		name: 'textColor',
		title: __('Text Color', 'responsive-menu'),
		icon: textColor,
	},
	{
		name: 'tablet',
		title: __('Tablet', 'responsive-menu'),
		icon: tablet,
		categories: ['devices'],
	},
	{
		name: 'title',
		title: __('Title', 'responsive-menu'),
		icon: title,
	},
	{
		name: 'tip',
		title: __('Tip', 'responsive-menu'),
		icon: tip,
	},
	{
		name: 'tool',
		title: __('Tool', 'responsive-menu'),
		icon: tool,
	},
	{
		name: 'trash',
		title: __('Trash', 'responsive-menu'),
		icon: trash,
	},
	{
		name: 'trendingDown',
		title: __('Trending Down', 'responsive-menu'),
		icon: trendingDown,
		categories: ['arrows'],
	},
	{
		name: 'trendingUp',
		title: __('Trending Up', 'responsive-menu'),
		icon: trendingUp,
		categories: ['arrows'],
	},
	{
		name: 'typography',
		title: __('Typography', 'responsive-menu'),
		icon: typography,
	},
	{
		name: 'undo',
		title: __('Undo', 'responsive-menu'),
		icon: undo,
		categories: ['arrows', 'editor'],
	},
	{
		name: 'ungroup',
		title: __('Ungroup', 'responsive-menu'),
		icon: ungroup,
		categories: ['editor'],
	},
	{
		name: 'unlock',
		title: __('Unlock', 'responsive-menu'),
		icon: unlock,
		categories: ['editor'],
	},
	{
		name: 'update',
		title: __('Update', 'responsive-menu'),
		icon: update,
	},
	{
		name: 'upload',
		title: __('Upload', 'responsive-menu'),
		icon: upload,
		categories: ['arrows'],
	},
	{
		isDefault: true,
		name: 'verse',
		title: __('Verse', 'responsive-menu'),
		icon: verse,
		categories: ['blocks'],
	},
	{
		name: 'video',
		title: __('Video', 'responsive-menu'),
		icon: video,
		categories: ['media'],
	},
	{
		name: 'warning',
		title: __('Warning', 'responsive-menu'),
		icon: warning,
	},
	{
		name: 'widget',
		title: __('Widget', 'responsive-menu'),
		icon: widget,
	},
];

const icons = [
	{
		isDefault: false,
		type: 'wordpress',
		title: __('WordPress', 'responsive-menu'),
		icons: [].concat(wordpressSocialIcons, wordpressIcons),
		categories: [
			{
				name: 'arrows',
				title: __('Arrows', 'responsive-menu'),
			},
			{
				name: 'blocks',
				title: __('Blocks', 'responsive-menu'),
			},
			{
				name: 'devices',
				title: __('Devices', 'responsive-menu'),
			},
			{
				name: 'editor',
				title: __('Editor', 'responsive-menu'),
			},
			{
				name: 'logos',
				title: __('Logos', 'responsive-menu'),
			},
			{
				name: 'media',
				title: __('Media', 'responsive-menu'),
			},
		],
	},
];

// Allow third parties to add their own icon types via filter.
export default function getIcons() {
	return applyFilters('gutenaTabs.icons', icons);
}
