<div id="responsive-menu-preview" style="
position: fixed;
top: 0;
left: 0;
right: 0;
z-index: 200000;
background: rgba(222, 75, 64, 0.89);
height: 50px;
line-height: 50px;
padding: 0 5%;
font-size: 14px;
color: white;
text-align: center;
font-family: Arial;
font-weight: bold;
"><?php _e(sprintf('Preview is only available with the Pro version - click %shere%s to upgrade today.', '<a style="text-decoration: underline; color: white;" href="https://responsive.menu/why-go-pro/?utm_source=free-plugin&utm_medium=preview&utm_campaign=free-plugin-preview" target="_blank">', '</a>'), 'responsive-menu'); ?></div>
