<?php

use ResponsiveMenu\Formatters\Tabs as Tabs;
use ResponsiveMenu\Formatters\Text as Text;

?>
<div class="wrap">
  <div id="poststuff">
      <div id="postbox-container" class="postbox-container">
      	<div class="tabs_container">
      		<?php Tabs::render($l['options']); ?>
          <a id="tab_import_export" class="tab page-title-action"><?php _e('Import/Export', 'responsive-menu') ?></a>
      	</div> <!-- tabs_container -->
        <?php if(isset($l['flash']['success'])): ?>
          <div class="updated notice notice-success is-dismissible" id="message">
            <p><?php _e($l['flash']['success'], 'responsive-menu'); ?></p>
            <button class="notice-dismiss" type="button">
              <span class="screen-reader-text">
              <?php _e('Dismiss this notice', 'responsive-menu') ?>.
              </span>
            </button>
          </div> <!-- updated -->
        <?php endif; ?>
      <?php if(isset($l['flash']['errors'])): ?>
        <div class="notice notice-error is-dismissible" id="message">
          <ul>
                    <?php foreach($l['flash']['errors'] as $error): ?>
                      <li><?php _e($error, 'responsive-menu'); ?></li>
                    <?php endforeach; ?>
                    </ul>
          <button class="notice-dismiss" type="button">
            <span class="screen-reader-text">
            <?php _e('Dismiss this notice', 'responsive-menu') ?>.
            </span>
          </button>
        </div>
      <?php endif; ?>
      <div id="all_options_container">
        <div class="meta-box-sortables ui-sortable" id="normal-sortables">
        	<form action="" method="post" enctype="multipart/form-data">
            <input type="submit" class="button submit" name="responsive_menu_submit" value="Update Options" style="display: none;" />
        		<?php $t=1; foreach(Tabs::getTabs($l['options']) as $key => $val): ?>
      			     <div class="tab_container tab_container_<?php echo $t; ?>" id="tab_container_<?php echo $key; ?>">
                   <?php foreach(Tabs::getSubTabs($key, $l['options']) as $tab_name): ?>
                      <div class="postbox" id="postbox_<?php echo explode('.',$tab_name)[1]; ?>">
                        <div class="handlediv">
                          <button aria-expanded="true" class="button-link" type="button"><span class="screen-reader-text">Toggle panel: Location</span><span aria-hidden="true" class="toggle-indicator"></span></button>
                        </div>
                        <h2 class="ui-sortable-handle hndle"><?php echo $val; ?> &raquo; <?php Text::underscoreToWord(explode('.',$tab_name)[1]); ?></h2>
                				<div class="inside">
                          <table class="widefat">
                  					<?php $i=0; foreach(Tabs::getTabOptions($tab_name, $l['options']) as $option) : ?>
                  						<tr class="<?php echo $option->isPro() ? 'pro_option' : ''; ?>"
                                id="<?php echo $option->getName(); ?>_container">
                							       <td><div class="label"><?php Text::underscoreToWord($option->getName()) ?></div><span class="description"><?php echo $option->getLabel(); ?></span></td>
              							         <td><?php $option->getFormComponent()->render($option); $i++; ?></td>
                                </tr>
                  					<?php endforeach; ?>
                          </table> <!-- .widefat -->
                				</div> <!-- .inside -->
                    </div> <!-- .postbox -->
                <?php endforeach; ?>
              </div> <!-- .tab_container -->
        		<?php $t++; endforeach; ?>
            <div class="tab_container tab_container_import_export" id="tab_container_import_export">
                 <div class="postbox" id="postbox_import_export">
                   <div class="handlediv">
                     <button aria-expanded="true" class="button-link" type="button"><span class="screen-reader-text">Toggle panel: Location</span><span aria-hidden="true" class="toggle-indicator"></span></button>
                   </div>
                   <h2 class="ui-sortable-handle hndle"><?php _e('Import/Export', 'responsive-menu') ?></h2>
                   <div class="inside">
                     <table class="widefat">
                         <tr id="import_container">
                                <td><div class="label"><?php _e('Import', 'responsive-menu') ?></div><span class="description"></span></td>
                                <td>
                                  <input type="file" name="responsive_menu_import_file" />
                                  <input type="submit" class="button submit" name="responsive_menu_import" value="Import Options" /></td>
                        </tr>
                         <tr id="export_container">
                                <td><div class="label"><?php _e('Export', 'responsive-menu') ?></div><span class="description"></span></td>
                                <td><input type="submit" class="button submit" name="responsive_menu_export" value="Export Options" /></td>
                         </tr>
                     </table> <!-- .widefat -->
                   </div> <!-- .inside -->
               </div> <!-- .postbox -->
         </div> <!-- .tab_container -->
        		<input type="submit" class="button submit" name="responsive_menu_submit" value="<?php _e('Update Options', 'responsive-menu') ?>" />
        		<input type="submit" class="button submit" name="responsive_menu_reset" value="<?php _e('Reset Options', 'responsive-menu') ?>" />
        	</form>
        </div> <!-- #normal-sortables -->
      </div><!--#all_options_container
   --><div id="banner_area">
        Banner area
        <ul>
          <li>FontIcon Support</li>
          <li>Opacity colour option</li>
          <li>15+ button animations</li>
          <li>Desktop & Responsive menu configuration</li>
          <li>Header Bar</li>
        </ul>
        Buy now for only $14.99
      </div> <!-- #banner_area -->
    </div> <!-- #postbox-container -->
  </div> <!-- #poststuff -->
</div> <!-- #wrap -->
