<?php

use ResponsiveMenu\Formatters\Tabs as Tabs;
use ResponsiveMenu\Formatters\Text as Text;
// This is horrible!
include dirname(dirname(dirname(__FILE__))) . '/config/admin_ordering.php';

$tabs = new ResponsiveMenu\ViewModels\Components\Admin\Tabs($order_mapping);
$boxes = new ResponsiveMenu\ViewModels\Components\Admin\Boxes($order_mapping, $l['options']);

?>
<div class="wrap">
  <div id="poststuff">
      <div id="postbox-container" class="postbox-container">
        <?php if(isset($l['flash']['success'])): ?>
          <div class="updated notice notice-success is-dismissible" id="message">
            <p><?php _e($l['flash']['success'], 'responsive-menu'); ?></p>
            <button class="notice-dismiss" type="button">
              <span class="screen-reader-text">
              <?php _e('Dismiss this notice', 'responsive-menu') ?>.
              </span>
            </button>
          </div> <!-- updated -->
        <?php endif; ?>
      <?php if(isset($l['flash']['errors'])): ?>
        <div class="notice notice-error is-dismissible" id="message">
          <ul>
                    <?php foreach($l['flash']['errors'] as $error): ?>
                      <li><?php _e($error, 'responsive-menu'); ?></li>
                    <?php endforeach; ?>
                    </ul>
          <button class="notice-dismiss" type="button">
            <span class="screen-reader-text">
            <?php _e('Dismiss this notice', 'responsive-menu') ?>.
            </span>
          </button>
        </div>
      <?php endif; ?>

      <div class="tabs_container">
        <?php echo $tabs->render(); ?>
      </div>

      <div class="key-container">
        <a href="http://responsive.menu/pricing/">
          <div class="key key-pro"><span>PRO</span>Only available in Pro version</div>
          <div class="key key-semi-pro"><span>SEMI PRO</span>Fully unlocked in Pro version (i.e - opacity selection for colours)</div>
        </a>
      </div>

  		<div class="upgrade-notes">
  			<div class="upgrade-notes-title">Welcome to Responsive Menu 3.0</div>
  			<div class="upgrade-notes-content">
          As this is a brand new version, there are over 14,000 combinations of options so squashing bugs is not an easy task and some may still exist. Therefore, please report any bugs to us <a href="https://responsive.menu/contact/" target="_blank">here</a> and we will deal with them quickly.<br /><br />
          For an upgrade guide, please check out <a href="https://responsive.menu/upgrading-from-version-2-to-version-3" target="_blank">this page</a>.
        </div>
        <div class="upgrade-notes-close">x</div>
  		</div>

      <div id="all_options_container">
        <div class="meta-box-sortables ui-sortable" id="normal-sortables">
        	<form action="" method="post" enctype="multipart/form-data">
            <input type="submit" class="button submit" name="responsive_menu_submit" value="Update Options" style="display: none;" />
            <div id="options_list_container">
              <?php echo $boxes->render(); ?>
            </div>
        		<input type="submit" id="responsive_menu_submit" class="button submit" name="responsive_menu_submit" value="<?php _e('Update Options', 'responsive-menu') ?>" />
        	</form>
        </div> <!-- #normal-sortables -->
      </div><!--#all_options_container
   --><div id="banner_area">
       <div id="upgrade_banner">
            <?php _e('Upgrade today to unlock the following features:', 'responsive-menu'); ?>
            <ul>
              <li><?php _e('Font Awesome Icon Support', 'responsive-menu'); ?></li>
              <li><?php _e('Opacity Option for all Colours', 'responsive-menu'); ?></li>
              <li><?php _e('15+ Button Animations', 'responsive-menu'); ?></li>
              <li><?php _e('Style Desktop Menu Too', 'responsive-menu'); ?></li>
              <li><?php _e('Header Bar', 'responsive-menu'); ?></li>
              <li><?php _e('And much more', 'responsive-menu'); ?></li>
            </ul>
            <a target="_blank" href="http://responsive.menu/why-go-pro" class="button"><?php _e('Upgrade Now', 'responsive-menu'); ?></a>
          </div>
          <div id="docs_banner">
            <?php _e('Confused? Check out our documentation', 'responsive-menu'); ?>
            <a target="_blank" href="https://responsive.menu/docs" class="button"><?php _e('View Docs', 'responsive-menu'); ?></a>
          </div>
      </div> <!-- #banner_area -->
    </div> <!-- #postbox-container -->
  </div> <!-- #poststuff -->
</div> <!-- #wrap -->
