<?php $button_title = $l['options']['button_title']; ?>
<?php $button_title_pos = $l['options']['button_title_position']; ?>
<?php $button_title_html = $button_title != '' ? '<span class="hamburger-label hamburger-label-'.$button_title_pos.'">'.$button_title.'</span>' : ''; ?>
<?php $accessible = in_array($button_title_pos, array('left', 'right')) ? 'hamburger--accessible' : ''; ?>

<button id="responsive-menu-button"
        class="hamburger
        <?php echo $accessible; ?>
        hamburger--<?php echo $l['options']['button_click_animation']; ?>"
        type="button"
        aria-label="Menu"
        aria-controls="navigation">
  <?php echo in_array($button_title_pos, array('top', 'left')) ? $button_title_html : ''; ?>
  <span class="hamburger-box">
    <span class="hamburger-inner"></span>
  </span>
  <?php echo in_array($button_title_pos, array('bottom', 'right')) ? $button_title_html : ''; ?>
</button>
