<div id="responsive-menu-container"
  class="<?php echo $this->options['animation_type']; ?>-<?php echo $this->options['menu_appear_from']; ?>">
  <div id="responsive-menu-wrapper">
    <div id="responsive-menu-title"><?php echo $this->options['menu_title']; ?></div>
    <?php echo $this->data['menu']; ?>
    <?php if($this->options['menu_remove_search_box'] != 'on'): ?>
      <div id="responsive-menu-search-box">
        <?php $action = function_exists( 'icl_get_home_url' ) ? icl_get_home_url() : get_home_url(); ?>
        <form action="<?php echo $action; ?>" class="responsive-menu-search-form" role="search">
          <input type="search" name="s" placeholder="<?php _e( 'Search', 'responsive-menu' ); ?>" class="responsive-menu-search-box">
        </form>
      </div>
    <?php endif; ?>
    <?php if($this->options['menu_additional_content']->getValue()): ?>
      <div id="responsive-menu-additional-content">
        <?php echo do_shortcode($this->options['menu_additional_content']); ?>
      </div>
    <?php endif; ?>
  </div>
</div>
<?php if($this->options['menu_overlay'] == 'on') : ?>
  <div id="responsive-menu-mask"></div>
<?php endif; ?>
